### PR TITLE
use the find library method from ctypes.util to find the shared library

### PR DESCRIPTION
**Pull request by TomHodson**
CDLL("libngspice.so") fails on my mac because the libraries are really at "/usr/local/lib/libngspice.dylib", using find_library seems to fix the issue though I don't know if this is the best method.

### CODE REVIEW

**Comment by ignamv** [comment]
Thanks! What platforms have you tested it on? I can do Linux if you haven't already.

**Comment by TomHodson** [comment]
I've only tested on OSX, in retrospect maybe a better choice would be to
detect OSX specifically and use find_library for only that case. I wouldn't
be surprised if find_library fails in the case of multiple libraries or
other cases that might occur in varying Linux distributions.

**Comment by ignamv** [comment]
Would you mind testing it again in OSX? In linux, find_library works with argument "ngspice" but not with "libngspice".

**Comment by TomHodson** [comment]
Yep, just checked 
`spice = CDLL(find_library('ngspice'))`
works for me on OSX 10.12 with libngspice installed via brew.

**Pull request merged**
