### PR TITLE
Tweak examples

### PR DESCRIPTION
**Pull request by endolith**
Change lowpass example's graph
Center the cutoff frequency
Magnitude and phase plots in normal Bode plot layout on top of each other with same freq axis instead of side by side

Float format for NPN example labels: I was getting something like "1.200000000002" in my graph

also PEP8 fixes to all examples

### CODE REVIEW

**Comment by endolith** [comment]
You gave me collaborator permission, does that mean you're ok with this?  I don't see any contact information for you.  

Are you ok with me making other changes, too?  If it were my project, I'd:

- Change the examples to use the more Pythonic functions: `ngspyce.ac(mode='dec', npoints=5, fstart=1e3, fstop=10e6)`
- Add SciPy-style docstrings with Parameters and Returns
- Add more pythonic functions for noise analysis, etc.
- Make everything [PEP8](https://www.python.org/dev/peps/pep-0008/) compliant, so it stops showing errors in Spyder :)
- Maybe make the pythonic functions take strings or numbers for start and stop frequency, so `fstop='10MHz'` would work as expected?

Are you ok with things like this?  Should I submit them as PRs first?

**Comment by ignamv** [comment]
Those all sound great. The last one looks like a job for pint (
https://pint.readthedocs.io/ )

**Comment by endolith** [comment]
Well I wasn't thinking of unit conversions, just simple parsing of the string.  

So this one can be merged?

**Comment by endolith** [comment]
Added some more changes to examples

**Pull request merged**
