### PR TITLE
ENH: Add basic Windows support

### LINKED ISSUE #5: ngspyce using ngspice.dll under windows ?
Hi,

I compile a windows x64 based `ngspice.dll` for ngspyce and modify line 12 of `ngspyce.py` as:

```
spice = CDLL('ngspice.dll')
```

I placed all `ngspice` binaries and `ngspice.dll` in `D:/Tools/spice/bin`, and set up the `PATH` environment of windows as `D:\Tools\spice\bin`. `ngspyce` can be loaded and it can find the dll!

In order to find `spinit` file for ngspice, I set `SPICE_SCRIPTS` of windows to `D:\Tools\spice\share\ngspice\scripts`, and modify `spinit` as

```
* For SPICE2 POLYs, edit the below line to point to the location 
* of your codemodel.

 codemodel D:/Tools/Spice/lib/ngspice/spice2poly.cm

* The other codemodels
 codemodel d:/Tools/Spice/lib/ngspice/analog.cm
 codemodel d:/Tools/Spice/lib/ngspice/digital.cm
 codemodel d:/Tools/Spice/lib/ngspice/xtradev.cm
 codemodel d:/Tools/Spice/lib/ngspice/xtraevt.cm
```

all the examples, `lowpass_filter.py` and `npn.py` work fine ! But it keeps complaining

```
ERROR:ngspice:Error: Library D:/Tools/Spice/lib/ngspice/spice2poly.cm couldn't be loaded!
ERROR:ngspice:Error: Library d:/Tools/Spice/lib/ngspice/analog.cm couldn't be loaded!
ERROR:ngspice:Error: Library d:/Tools/Spice/lib/ngspice/digital.cm couldn't be loaded!
ERROR:ngspice:Error: Library d:/Tools/Spice/lib/ngspice/xtradev.cm couldn't be loaded!
ERROR:ngspice:Error: Library d:/Tools/Spice/lib/ngspice/xtraevt.cm couldn't be loaded!
```

**the `quad.py` failed because `spice2poly.cm` can not be loaded.**

Can we solve it and enable `ngspyce` for windows ?

BTW: when simulating `quad.py`, ngspice seems to be much slower than `LTSpice`.

### PR DESCRIPTION
**Pull request by endolith**
This assumes a particular directory structure (but then again, so does
ngspice's spinit file).

It changes working directory to load the DLL and dependencies without
problems.  This might not be optimal, but it works.

I tried to add some guessing of 32-bit and 64-bit, and in case system drive is not C:\ but I didn't test anything except 64-bit C:\

Fixes #5

### CODE REVIEW

**Comment by endolith** [comment]
Hmm I guess this is including all changes I've made to my master branch.  Not sure how best to handle that.

**Comment by ignamv** [comment]
Looks good. Do the tests pass on Linux?

**Comment by endolith** [comment]
I'll try to compile ngspice for Linux, never tried that before

**Comment by endolith** [comment]
Hmm, I cloned the ngspice git repo (`git clone https://git.code.sf.net/p/ngspice/ngspice ngspice
`) and tried `./configure --with-ngshared` but that doesn't work. there's a `configure.ac`, though. Did this change or am I using the wrong repo?

**Comment by endolith** [comment]
Ok I got ngspice-26.tar.gz instead and the instructions worked this time.  `/usr/local/lib/libngspice.so` exists now, but I still get `OSError: libngspice.so: cannot open shared object file: No such file or directory`

**Comment by endolith** [comment]
If I edit `/usr/local/lib/python3.5/dist-packages/ngspyce/ngspyce.py`  and change the line to `spice = CDLL('/usr/local/lib/libngspice.so')` then ngspyce works, but the tests for the .cm files don't work.  So I guess they're not enabled by default?  So

- if those are optional to ngspyce, change the tests into warnings
- if those are required for ngspyce, change the build instructions to enable them

In my testing, many spice models require the spice2poly.cm to be enabled, and they weren't working in Windows until I figured out the paths, etc. so I wrote test for them.

**Comment by ignamv** [comment]
Don't worry, I'll test it in Linux.

**Comment by ignamv** [comment]
Thank you!

**Comment by endolith** [comment]
So are there things you'd be ok with me merging directly, or should I always file pull requests?  Unfinished stuff is in https://github.com/endolith/ngspyce/tree/experimenting

**Comment by ignamv** [comment]
I'd prefer to look at any changes that might break something, and at least run the tests on Linux.

By the way, what are you using ngspyce for?

**Comment by endolith** [comment]
Ok I'll just file PRs.  :)

I've only done some experiments so far, but I'd like to automate some circuit design stuff, like optimizing resistor values to maximize THD+noise for a circuit, etc.

condenser mic capsule noise vs bias resistor ngspyce

bc547 mpl2

2n2222 220 ohm

**Pull request merged**
